apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-application
  namespace: argocd
spec:
  project: default

  # Nguồn: Trỏ đến "manifest-repo"
  source:
    repoURL: https://github.com/danny2708/k8s-manifests.git
    targetRevision: HEAD # Theo dõi nhánh main
    path: . 

  # Đích: Triển khai ở đâu
  destination:
    server: https://kubernetes.default.svc # 'default.svc' nghĩa là chính cluster này
    namespace: default # Triển khai vào namespace 'default'

  # Chính sách đồng bộ: Tự động
  syncPolicy:
    automated:
      prune: true    # Xóa tài nguyên cũ không còn trong Git
      selfHeal: true # Tự động sửa chữa nếu trạng thái cluster khác Git
